from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import html
import json
import math
import random
from datetime import datetime, timezone


TASKS = {
    "handoff": "Collaborative handoff",
    "clutter_tool": "Clutter clearing + tool retrieval",
    "drawer_tool": "Drawer opening + tool retrieval",
    "language": "Zero-shot language retarget",
}


@dataclass(frozen=True)
class SimRunConfig:
    run_id: str
    task: str
    output_dir: Path
    frames: int = 14
    seed: int = 145
    width: int = 1440
    height: int = 900
    render_style: str = "cinematic"


@dataclass(frozen=True)
class Pose:
    x: float
    y: float
    theta: float = 0.0


@dataclass(frozen=True)
class SimFrame:
    index: int
    time_s: float
    phase: str
    robot_a: Pose
    robot_b: Pose
    tool: Pose
    drawer_open: float
    safety_veto: str | None
    success_estimate: float
    intent_age_ms: float


def safe_run_id(value: str) -> str:
    keep: list[str] = []
    dash = False
    for char in value.strip().lower():
        if char.isalnum() or char in {"_", "-"}:
            keep.append(char)
            dash = char == "-"
        elif not dash:
            keep.append("-")
            dash = True
    return "".join(keep).strip("-") or "sim-run"


def simulate_run(config: SimRunConfig) -> dict[str, object]:
    if config.task not in TASKS:
        raise ValueError(f"unknown task {config.task!r}; choose one of {sorted(TASKS)}")
    if config.frames < 2:
        raise ValueError("frames must be >= 2")

    run_id = safe_run_id(config.run_id)
    run_dir = config.output_dir / run_id
    frames_dir = run_dir / "frames"
    frames_dir.mkdir(parents=True, exist_ok=True)

    rng = random.Random(config.seed)
    frames = generate_frames(config.task, config.frames, rng)
    frame_records: list[dict[str, object]] = []
    for frame in frames:
        frame_path = frames_dir / f"frame_{frame.index:04d}.svg"
        if config.render_style == "technical":
            svg = render_frame(frame, config.task, config.width, config.height)
        elif config.render_style == "cinematic":
            svg = render_cinematic_frame(frame, config.task, config.width, config.height)
        else:
            raise ValueError("render_style must be 'technical' or 'cinematic'")
        frame_path.write_text(svg, encoding="utf-8")
        frame_records.append(
            {
                "file": str(frame_path.relative_to(run_dir)),
                "time_s": frame.time_s,
                "phase": frame.phase,
                "drawer_open": round(frame.drawer_open, 3),
                "safety_veto": frame.safety_veto,
                "success_estimate": round(frame.success_estimate, 3),
                "intent_age_ms": round(frame.intent_age_ms, 1),
            }
        )

    write_sim_gallery(run_dir, frame_records)
    write_contact_sheet(run_dir, frame_records, config.width, config.height)
    manifest = {
        "run_id": run_id,
        "task": config.task,
        "task_label": TASKS[config.task],
        "created_at": datetime.now(timezone.utc).isoformat(),
        "seed": config.seed,
        "render_style": config.render_style,
        "frames": frame_records,
        "note": "Synthetic simulation frames generated by the repository reference simulator; not real robot camera data.",
    }
    (run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def generate_frames(task: str, count: int, rng: random.Random) -> list[SimFrame]:
    frames: list[SimFrame] = []
    for idx in range(1, count + 1):
        alpha = (idx - 1) / (count - 1)
        time_s = round(alpha * 18.0, 2)
        intent_age = 80.0 + 140.0 * abs(math.sin(alpha * math.pi * 2.0 + 0.4))
        veto: str | None = None
        drawer_open = 0.0
        success = 0.15 + 0.70 * alpha

        if task == "handoff":
            phase = _phase(alpha, ["APPROACH", "ALIGN", "FORCE_GATE", "TRANSFER", "RETREAT"])
            robot_a = Pose(270 + 160 * alpha, 415 - 45 * alpha, 0.1)
            robot_b = Pose(830 - 210 * alpha, 300 + 60 * alpha, 3.0)
            tool = Pose(445 + 155 * min(1.0, max(0.0, (alpha - 0.35) / 0.45)), 385 + 5 * math.sin(alpha * 8))
            if 0.46 < alpha < 0.56:
                veto = "FORCE_GATE_ARMED"
            success = 0.25 + 0.55 * alpha
        elif task == "clutter_tool":
            phase = _phase(alpha, ["SCAN", "CLEAR_LEFT", "CLEAR_RIGHT", "GRASP_TOOL", "RETRIEVE"])
            robot_a = Pose(250 + 95 * math.sin(alpha * math.pi), 250 + 135 * alpha, 0.8)
            robot_b = Pose(790 - 190 * alpha, 520 - 140 * alpha, -2.5)
            tool = Pose(720 - 190 * alpha, 350 + 40 * math.sin(alpha * 4.0))
            if 0.25 < alpha < 0.36:
                veto = "PEER_EXCLUSION_CLIP"
            success = 0.22 + 0.50 * alpha
        elif task == "drawer_tool":
            phase = _phase(alpha, ["HANDLE_SEARCH", "CENTER_PULL", "RECENTER", "OPEN", "RETRIEVE"])
            robot_a = Pose(330 + 255 * alpha, 490 - 140 * alpha, -0.6)
            robot_b = Pose(780, 520 - 110 * alpha, -2.2)
            drawer_open = min(1.0, max(0.0, (alpha - 0.32) / 0.55))
            tool = Pose(820 - 170 * drawer_open, 258 + 6 * math.sin(alpha * 9.0))
            if 0.48 < alpha < 0.58:
                veto = "DRAWER_SIDE_LOAD"
                success -= 0.08
            success = 0.18 + 0.48 * alpha
        else:
            phase = _phase(alpha, ["LANGUAGE_GROUND", "ROLE_ASSIGN", "BASE_MOVE", "MANIPULATE", "VERIFY"])
            robot_a = Pose(230 + 220 * alpha, 180 + 130 * alpha, 0.6)
            robot_b = Pose(860 - 240 * alpha, 555 - 160 * alpha, 2.7)
            tool = Pose(670 - 80 * alpha, 300 + 110 * alpha)
            if intent_age > 205:
                veto = "STALE_INTENT_HOLD"
            success = 0.20 + 0.50 * alpha

        jitter = lambda amount: rng.uniform(-amount, amount)
        frames.append(
            SimFrame(
                index=idx,
                time_s=time_s,
                phase=phase,
                robot_a=Pose(robot_a.x + jitter(3), robot_a.y + jitter(3), robot_a.theta),
                robot_b=Pose(robot_b.x + jitter(3), robot_b.y + jitter(3), robot_b.theta),
                tool=Pose(tool.x + jitter(4), tool.y + jitter(4), tool.theta),
                drawer_open=drawer_open,
                safety_veto=veto,
                success_estimate=max(0.0, min(0.95, success)),
                intent_age_ms=intent_age,
            )
        )
    return frames


def _phase(alpha: float, phases: list[str]) -> str:
    idx = min(len(phases) - 1, int(alpha * len(phases)))
    return phases[idx]


def render_frame(frame: SimFrame, task: str, width: int, height: int) -> str:
    title = TASKS[task]
    body = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        "<style>text{font-family:Inter,Arial,sans-serif}.title{font-size:24px;font-weight:700;fill:#111827}.label{font-size:14px;fill:#334155}.small{font-size:12px;fill:#64748b}.hud{font-size:13px;fill:#0f172a}.wall{fill:#e2e8f0;stroke:#475569;stroke-width:3}.floor{fill:#f8fafc}.zone{fill:#dbeafe;stroke:#2563eb;stroke-width:1;opacity:.55}.danger{fill:#fee2e2;stroke:#dc2626;stroke-width:1}.drawer{fill:#fef3c7;stroke:#92400e;stroke-width:2}.clutter{fill:#cbd5e1;stroke:#64748b;stroke-width:1}.tool{fill:#f97316;stroke:#9a3412;stroke-width:2}.robotA{fill:#2563eb;stroke:#1e3a8a;stroke-width:3}.robotB{fill:#16a34a;stroke:#14532d;stroke-width:3}.arm{stroke:#0f172a;stroke-width:6;stroke-linecap:round}.grip{stroke:#111827;stroke-width:3}</style>",
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        text(32, 38, f"{title} · simulated frame {frame.index:02d}", "title", "start"),
        text(32, 63, "Synthetic AURORA simulator output, not real robot camera data", "small", "start"),
        '<rect x="40" y="90" width="760" height="560" rx="8" class="floor" stroke="#94a3b8" stroke-width="2"/>',
        '<rect x="70" y="128" width="700" height="36" class="wall"/>',
        '<rect x="70" y="602" width="700" height="26" class="wall"/>',
        '<rect x="70" y="128" width="30" height="500" class="wall"/>',
        '<rect x="740" y="128" width="30" height="500" class="wall"/>',
        '<rect x="118" y="196" width="176" height="82" rx="8" fill="#d1d5db" stroke="#64748b"/>',
        '<rect x="570" y="190" width="150" height="245" rx="8" fill="#e5e7eb" stroke="#64748b"/>',
        f'<rect x="{610 - 75 * frame.drawer_open:.1f}" y="230" width="{120 + 75 * frame.drawer_open:.1f}" height="68" rx="4" class="drawer"/>',
        '<rect x="360" y="330" width="128" height="82" rx="8" fill="#fde68a" stroke="#a16207"/>',
        '<ellipse cx="430" cy="370" rx="155" ry="115" class="zone"/>',
        '<circle cx="610" cy="370" r="92" class="danger" opacity=".35"/>',
    ]
    for i, (x, y, rot) in enumerate([(390, 350, 20), (420, 395, -15), (455, 345, 70), (500, 383, 35), (535, 335, -30)]):
        body.append(f'<rect x="{x}" y="{y}" width="{38 + i * 3}" height="{18 + (i % 2) * 12}" rx="4" class="clutter" transform="rotate({rot} {x} {y})"/>')
    body.append(render_tool(frame.tool, task))
    body.append(render_robot(frame.robot_a, "A", "robotA"))
    body.append(render_robot(frame.robot_b, "B", "robotB"))
    body.extend(render_hud(frame))
    body.extend(render_wrist_inset(frame, task))
    body.append("</svg>")
    return "\n".join(body)


def render_robot(pose: Pose, label: str, klass: str) -> str:
    arm_len = 62
    ex = pose.x + arm_len * math.cos(pose.theta)
    ey = pose.y + arm_len * math.sin(pose.theta)
    return "\n".join(
        [
            f'<circle cx="{pose.x:.1f}" cy="{pose.y:.1f}" r="34" class="{klass}"/>',
            f'<line x1="{pose.x:.1f}" y1="{pose.y:.1f}" x2="{ex:.1f}" y2="{ey:.1f}" class="arm"/>',
            f'<line x1="{ex - 10:.1f}" y1="{ey - 9:.1f}" x2="{ex + 10:.1f}" y2="{ey + 9:.1f}" class="grip"/>',
            text(pose.x, pose.y + 5, f"R{label}", "label"),
        ]
    )


def render_tool(pose: Pose, task: str) -> str:
    if task == "handoff":
        return f'<rect x="{pose.x-34:.1f}" y="{pose.y-8:.1f}" width="68" height="16" rx="8" class="tool"/><circle cx="{pose.x+24:.1f}" cy="{pose.y:.1f}" r="15" fill="#fde68a" stroke="#9a3412" stroke-width="2"/>'
    if task == "drawer_tool":
        return f'<path d="M {pose.x-42:.1f} {pose.y:.1f} L {pose.x+34:.1f} {pose.y:.1f}" class="tool" stroke-width="9" stroke-linecap="round"/><circle cx="{pose.x+38:.1f}" cy="{pose.y:.1f}" r="12" class="tool"/>'
    return f'<path d="M {pose.x-38:.1f} {pose.y+15:.1f} L {pose.x+35:.1f} {pose.y-18:.1f}" class="tool" stroke-width="8" stroke-linecap="round"/><rect x="{pose.x+22:.1f}" y="{pose.y-28:.1f}" width="28" height="18" rx="3" class="tool"/>'


def render_hud(frame: SimFrame) -> list[str]:
    x, y = 840, 96
    veto = frame.safety_veto or "none"
    rows = [
        ("phase", frame.phase),
        ("intent age", f"{frame.intent_age_ms:.0f} ms"),
        ("drawer open", f"{frame.drawer_open:.2f}"),
        ("success est.", f"{frame.success_estimate:.2f}"),
        ("safety event", veto),
    ]
    body = [
        '<rect x="820" y="90" width="260" height="190" rx="8" fill="#f8fafc" stroke="#94a3b8"/>',
        text(950, 120, "Runtime telemetry", "label"),
    ]
    for idx, (key, value) in enumerate(rows):
        body.append(text(x, y + 56 + idx * 25, key, "small", "start"))
        body.append(text(1060, y + 56 + idx * 25, value, "hud", "end"))
    return body


def render_wrist_inset(frame: SimFrame, task: str) -> list[str]:
    body = [
        '<rect x="820" y="310" width="260" height="260" rx="8" fill="#111827" stroke="#475569" stroke-width="2"/>',
        text(950, 338, "synthetic wrist view", "small"),
        '<rect x="850" y="365" width="200" height="120" rx="6" fill="#374151"/>',
        '<path d="M 875 530 C 910 455, 995 455, 1030 530" fill="#94a3b8" stroke="#e5e7eb" stroke-width="2"/>',
        '<line x1="905" y1="505" x2="940" y2="452" stroke="#e5e7eb" stroke-width="8" stroke-linecap="round"/>',
        '<line x1="995" y1="452" x2="1030" y2="505" stroke="#e5e7eb" stroke-width="8" stroke-linecap="round"/>',
    ]
    if task == "drawer_tool":
        body.append(f'<rect x="{915 - 34 * frame.drawer_open:.1f}" y="404" width="{86 + 45 * frame.drawer_open:.1f}" height="34" rx="4" fill="#fbbf24" stroke="#92400e"/>')
        body.append('<circle cx="940" cy="421" r="8" fill="#111827"/>')
    elif task == "handoff":
        body.append('<rect x="912" y="410" width="78" height="18" rx="9" fill="#f97316" stroke="#fed7aa"/>')
    else:
        body.append('<path d="M 905 435 L 990 397" stroke="#f97316" stroke-width="8" stroke-linecap="round"/>')
    return body


def render_cinematic_frame(frame: SimFrame, task: str, width: int, height: int) -> str:
    """Render a cinematic pseudo-3D SVG frame for GitHub galleries."""

    sx = width / 1440.0
    sy = height / 900.0
    title = TASKS[task]
    a_iso = iso(frame.robot_a.x, frame.robot_a.y)
    b_iso = iso(frame.robot_b.x, frame.robot_b.y)
    tool_iso = iso(frame.tool.x, frame.tool.y)
    progress = min(1.0, max(0.0, (frame.index - 1) / 11.0))
    veto_color = "#ef4444" if frame.safety_veto else "#22c55e"
    label = frame.safety_veto or "NOMINAL"
    body = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 1440 900">',
        cinematic_defs(),
        '<rect width="1440" height="900" fill="url(#bg)"/>',
        '<rect width="1440" height="900" fill="url(#vignette)" opacity="0.95"/>',
        '<g filter="url(#softShadow)">',
        '<path d="M150 650 L590 290 L1185 495 L745 820 Z" fill="url(#floorGrad)" stroke="#4b5563" stroke-width="2"/>',
        '<path d="M150 650 L150 272 L590 80 L590 290 Z" fill="url(#wallLeft)" stroke="#334155" stroke-width="2"/>',
        '<path d="M590 80 L1185 285 L1185 495 L590 290 Z" fill="url(#wallRight)" stroke="#334155" stroke-width="2"/>',
        "</g>",
        render_floor_grid(),
        render_cinematic_furniture(frame.drawer_open),
        render_cinematic_clutter(task),
        render_sensor_volume(a_iso[0], a_iso[1], "#60a5fa", -42),
        render_sensor_volume(b_iso[0], b_iso[1], "#34d399", 32),
        render_cinematic_tool(tool_iso[0], tool_iso[1], task),
        render_cinematic_robot(a_iso[0], a_iso[1], frame.robot_a.theta, "A", "#3b82f6", "#93c5fd"),
        render_cinematic_robot(b_iso[0], b_iso[1], frame.robot_b.theta, "B", "#22c55e", "#86efac"),
        render_cinematic_paths(task, progress),
        render_cinematic_hud(frame, title, veto_color, label),
        render_wrist_camera_panel(frame, task),
        render_depth_panel(frame, task),
        '<rect x="0" y="0" width="1440" height="900" fill="url(#dust)" opacity="0.33"/>',
        '<rect x="0" y="0" width="1440" height="900" fill="none" stroke="#1e293b" stroke-width="18" opacity="0.55"/>',
        "</svg>",
    ]
    return "\n".join(body)


def cinematic_defs() -> str:
    return """
<defs>
  <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="#07111f"/>
    <stop offset="0.55" stop-color="#111827"/>
    <stop offset="1" stop-color="#172033"/>
  </linearGradient>
  <radialGradient id="vignette" cx="50%" cy="46%" r="70%">
    <stop offset="0" stop-color="#ffffff" stop-opacity="0.07"/>
    <stop offset="0.58" stop-color="#0f172a" stop-opacity="0"/>
    <stop offset="1" stop-color="#020617" stop-opacity="0.82"/>
  </radialGradient>
  <linearGradient id="floorGrad" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="#475569"/>
    <stop offset="0.45" stop-color="#334155"/>
    <stop offset="1" stop-color="#111827"/>
  </linearGradient>
  <linearGradient id="wallLeft" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="#1f2937"/>
    <stop offset="1" stop-color="#0f172a"/>
  </linearGradient>
  <linearGradient id="wallRight" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="#273449"/>
    <stop offset="1" stop-color="#111827"/>
  </linearGradient>
  <radialGradient id="lamp" cx="50%" cy="50%" r="50%">
    <stop offset="0" stop-color="#fef3c7" stop-opacity="0.60"/>
    <stop offset="1" stop-color="#fef3c7" stop-opacity="0"/>
  </radialGradient>
  <pattern id="dust" width="86" height="86" patternUnits="userSpaceOnUse">
    <circle cx="9" cy="18" r="1.1" fill="#e5e7eb" opacity="0.22"/>
    <circle cx="44" cy="51" r="1.5" fill="#f8fafc" opacity="0.18"/>
    <circle cx="75" cy="27" r="0.9" fill="#cbd5e1" opacity="0.18"/>
    <circle cx="23" cy="78" r="0.7" fill="#fef3c7" opacity="0.16"/>
  </pattern>
  <filter id="softShadow" x="-30%" y="-30%" width="160%" height="160%">
    <feDropShadow dx="0" dy="16" stdDeviation="12" flood-color="#020617" flood-opacity="0.45"/>
  </filter>
  <filter id="glow" x="-50%" y="-50%" width="200%" height="200%">
    <feGaussianBlur stdDeviation="5" result="coloredBlur"/>
    <feMerge>
      <feMergeNode in="coloredBlur"/>
      <feMergeNode in="SourceGraphic"/>
    </feMerge>
  </filter>
</defs>
"""


def iso(x: float, y: float) -> tuple[float, float]:
    return (335 + 0.78 * x + 0.48 * y, 118 + 0.27 * x + 0.58 * y)


def render_floor_grid() -> str:
    lines: list[str] = []
    for offset in range(-4, 9):
        x1, y1 = iso(70 + offset * 86, 95)
        x2, y2 = iso(70 + offset * 86, 760)
        lines.append(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" stroke="#64748b" stroke-width="1" opacity="0.18"/>')
    for offset in range(0, 9):
        x1, y1 = iso(80, 130 + offset * 78)
        x2, y2 = iso(860, 130 + offset * 78)
        lines.append(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" stroke="#94a3b8" stroke-width="1" opacity="0.14"/>')
    lines.append('<ellipse cx="965" cy="318" rx="290" ry="190" fill="url(#lamp)" opacity="0.55"/>')
    return "\n".join(lines)


def render_cinematic_furniture(drawer_open: float) -> str:
    drawer_x, drawer_y = iso(650 - 74 * drawer_open, 205)
    counter_x, counter_y = iso(150, 170)
    table_x, table_y = iso(350, 380)
    return "\n".join(
        [
            f'<g filter="url(#softShadow)"><path d="M{counter_x:.1f} {counter_y:.1f} l160 52 l-92 76 l-160 -52z" fill="#64748b" stroke="#cbd5e1" opacity="0.92"/><path d="M{counter_x+10:.1f} {counter_y+26:.1f} l126 41 l-60 48 l-125 -42z" fill="#94a3b8" opacity="0.35"/></g>',
            f'<g filter="url(#softShadow)"><path d="M{table_x:.1f} {table_y:.1f} l150 52 l-105 86 l-150 -52z" fill="#92400e" stroke="#fbbf24" opacity="0.86"/><path d="M{table_x+10:.1f} {table_y+17:.1f} l128 44 l-82 66 l-128 -44z" fill="#b45309" opacity="0.65"/></g>',
            f'<g filter="url(#softShadow)"><path d="M{drawer_x:.1f} {drawer_y:.1f} l190 64 l-74 58 l-190 -64z" fill="#f59e0b" stroke="#fef3c7" stroke-width="2"/><path d="M{drawer_x+44:.1f} {drawer_y+50:.1f} l86 29 l-16 15 l-86 -29z" fill="#111827" opacity="0.72"/><circle cx="{drawer_x+113:.1f}" cy="{drawer_y+69:.1f}" r="8" fill="#fef3c7"/></g>',
        ]
    )


def render_cinematic_clutter(task: str) -> str:
    seed = {"handoff": 11, "clutter_tool": 29, "drawer_tool": 43, "language": 71}[task]
    rng = random.Random(seed)
    parts = []
    colors = ["#94a3b8", "#64748b", "#facc15", "#a3a3a3", "#f97316", "#475569"]
    for idx in range(24):
        x = rng.uniform(220, 640)
        y = rng.uniform(245, 610)
        cx, cy = iso(x, y)
        w = rng.uniform(22, 64)
        h = rng.uniform(10, 34)
        rot = rng.uniform(-28, 28)
        color = colors[idx % len(colors)]
        opacity = 0.62 if idx % 5 else 0.86
        parts.append(f'<rect x="{cx:.1f}" y="{cy:.1f}" width="{w:.1f}" height="{h:.1f}" rx="5" fill="{color}" stroke="#111827" opacity="{opacity}" transform="rotate({rot:.1f} {cx:.1f} {cy:.1f})"/>')
    return "\n".join(parts)


def render_sensor_volume(x: float, y: float, color: str, angle: float) -> str:
    return "\n".join(
        [
            f'<path d="M{x:.1f} {y:.1f} l{180 * math.cos(math.radians(angle-18)):.1f} {180 * math.sin(math.radians(angle-18)):.1f} q46 -30 {180 * math.cos(math.radians(angle+18)):.1f} {180 * math.sin(math.radians(angle+18)):.1f} z" fill="{color}" opacity="0.10" filter="url(#glow)"/>',
            f'<circle cx="{x:.1f}" cy="{y:.1f}" r="74" fill="none" stroke="{color}" stroke-width="2" opacity="0.20" stroke-dasharray="6 10"/>',
        ]
    )


def render_cinematic_robot(x: float, y: float, theta: float, label: str, color: str, light: str) -> str:
    arm_x = x + 78 * math.cos(theta)
    arm_y = y + 40 * math.sin(theta)
    grip_x = arm_x + 42 * math.cos(theta + 0.15)
    grip_y = arm_y + 24 * math.sin(theta + 0.15)
    return "\n".join(
        [
            f'<ellipse cx="{x:.1f}" cy="{y+42:.1f}" rx="72" ry="34" fill="#020617" opacity="0.42"/>',
            f'<g filter="url(#softShadow)"><ellipse cx="{x:.1f}" cy="{y:.1f}" rx="58" ry="38" fill="{color}" stroke="{light}" stroke-width="4"/><ellipse cx="{x-8:.1f}" cy="{y-10:.1f}" rx="28" ry="13" fill="{light}" opacity="0.38"/><circle cx="{x+30:.1f}" cy="{y-12:.1f}" r="10" fill="#e0f2fe"/><text x="{x:.1f}" y="{y+8:.1f}" font-family="Inter,Arial,sans-serif" font-size="18" font-weight="700" text-anchor="middle" fill="#f8fafc">R{label}</text></g>',
            f'<path d="M{x+18:.1f} {y+4:.1f} Q{arm_x-10:.1f} {arm_y-28:.1f} {arm_x:.1f} {arm_y:.1f}" stroke="#cbd5e1" stroke-width="14" stroke-linecap="round" fill="none" filter="url(#softShadow)"/>',
            f'<path d="M{arm_x:.1f} {arm_y:.1f} Q{grip_x-12:.1f} {grip_y-10:.1f} {grip_x:.1f} {grip_y:.1f}" stroke="#94a3b8" stroke-width="11" stroke-linecap="round" fill="none"/>',
            f'<path d="M{grip_x-14:.1f} {grip_y-9:.1f} L{grip_x+15:.1f} {grip_y+10:.1f} M{grip_x-7:.1f} {grip_y+12:.1f} L{grip_x+20:.1f} {grip_y-7:.1f}" stroke="#f8fafc" stroke-width="4" stroke-linecap="round"/>',
        ]
    )


def render_cinematic_tool(x: float, y: float, task: str) -> str:
    if task == "handoff":
        shape = f'<rect x="{x-44:.1f}" y="{y-9:.1f}" width="88" height="18" rx="9" fill="#fb923c" stroke="#fed7aa" stroke-width="3"/><circle cx="{x+36:.1f}" cy="{y:.1f}" r="20" fill="#fde68a" stroke="#fb923c" stroke-width="3" filter="url(#glow)"/>'
    elif task == "drawer_tool":
        shape = f'<path d="M{x-54:.1f} {y+4:.1f} L{x+42:.1f} {y-10:.1f}" stroke="#fb923c" stroke-width="11" stroke-linecap="round"/><circle cx="{x+48:.1f}" cy="{y-12:.1f}" r="15" fill="#f97316" stroke="#fed7aa" stroke-width="3"/>'
    else:
        shape = f'<path d="M{x-48:.1f} {y+24:.1f} L{x+44:.1f} {y-22:.1f}" stroke="#fb923c" stroke-width="10" stroke-linecap="round"/><rect x="{x+30:.1f}" y="{y-35:.1f}" width="38" height="22" rx="4" fill="#fdba74" stroke="#9a3412" stroke-width="3"/>'
    return f'<g filter="url(#softShadow)">{shape}</g>'


def render_cinematic_paths(task: str, progress: float) -> str:
    if task == "drawer_tool":
        d = "M675 710 C700 625, 775 570, 825 512 C875 455, 900 405, 944 350"
    elif task == "handoff":
        d = "M606 675 C652 610, 718 575, 775 548 C845 515, 900 480, 955 430"
    elif task == "clutter_tool":
        d = "M620 645 C675 575, 735 540, 800 508 C874 470, 940 440, 1005 392"
    else:
        d = "M545 515 C642 560, 735 540, 818 487 C903 430, 970 398, 1040 362"
    return "\n".join(
        [
            f'<path d="{d}" fill="none" stroke="#38bdf8" stroke-width="5" opacity="0.16"/>',
            f'<path d="{d}" fill="none" stroke="#67e8f9" stroke-width="3" opacity="0.72" stroke-dasharray="{max(30, 260 * progress):.1f} 800" filter="url(#glow)"/>',
        ]
    )


def render_cinematic_hud(frame: SimFrame, title: str, veto_color: str, label: str) -> str:
    success_w = 210 * frame.success_estimate
    age_w = min(210, 210 * frame.intent_age_ms / 420.0)
    drawer_w = 210 * frame.drawer_open
    return "\n".join(
        [
            '<g filter="url(#softShadow)">',
            '<rect x="1040" y="54" width="340" height="312" rx="18" fill="#0f172a" opacity="0.88" stroke="#334155"/>',
            f'<text x="1064" y="91" font-family="Inter,Arial,sans-serif" font-size="21" font-weight="700" fill="#f8fafc">{html.escape(title)}</text>',
            '<text x="1064" y="119" font-family="Inter,Arial,sans-serif" font-size="12" fill="#94a3b8">AURORA dual-rate synthetic telemetry</text>',
            f'<rect x="1064" y="145" width="112" height="28" rx="14" fill="{veto_color}" opacity="0.23" stroke="{veto_color}"/><text x="1120" y="164" font-family="Inter,Arial,sans-serif" font-size="12" font-weight="700" text-anchor="middle" fill="{veto_color}">{html.escape(label)}</text>',
            f'<text x="1064" y="206" font-family="Inter,Arial,sans-serif" font-size="13" fill="#cbd5e1">phase</text><text x="1360" y="206" font-family="Inter,Arial,sans-serif" font-size="13" text-anchor="end" fill="#f8fafc">{html.escape(frame.phase)}</text>',
            '<text x="1064" y="238" font-family="Inter,Arial,sans-serif" font-size="13" fill="#cbd5e1">success estimate</text>',
            '<rect x="1064" y="250" width="210" height="9" rx="5" fill="#1e293b"/>',
            f'<rect x="1064" y="250" width="{success_w:.1f}" height="9" rx="5" fill="#22c55e"/>',
            '<text x="1064" y="286" font-family="Inter,Arial,sans-serif" font-size="13" fill="#cbd5e1">intent age</text>',
            '<rect x="1064" y="298" width="210" height="9" rx="5" fill="#1e293b"/>',
            f'<rect x="1064" y="298" width="{age_w:.1f}" height="9" rx="5" fill="#f59e0b"/>',
            '<text x="1064" y="334" font-family="Inter,Arial,sans-serif" font-size="13" fill="#cbd5e1">drawer open</text>',
            '<rect x="1064" y="346" width="210" height="9" rx="5" fill="#1e293b"/>',
            f'<rect x="1064" y="346" width="{drawer_w:.1f}" height="9" rx="5" fill="#38bdf8"/>',
            f'<text x="1370" y="334" font-family="Inter,Arial,sans-serif" font-size="13" text-anchor="end" fill="#f8fafc">t={frame.time_s:.1f}s</text>',
            "</g>",
        ]
    )


def render_wrist_camera_panel(frame: SimFrame, task: str) -> str:
    drawer = frame.drawer_open
    tool_shift = 48 * min(1.0, frame.success_estimate)
    event = "#ef4444" if frame.safety_veto else "#22c55e"
    task_shape = (
        f'<rect x="{1120 - 55 * drawer:.1f}" y="520" width="{112 + 70 * drawer:.1f}" height="52" rx="6" fill="#f59e0b" stroke="#fef3c7"/>'
        if task == "drawer_tool"
        else f'<path d="M1110 {548-tool_shift:.1f} L1228 {512-tool_shift:.1f}" stroke="#fb923c" stroke-width="12" stroke-linecap="round"/>'
    )
    return "\n".join(
        [
            '<g filter="url(#softShadow)">',
            '<rect x="1040" y="398" width="340" height="226" rx="18" fill="#020617" opacity="0.94" stroke="#334155"/>',
            '<text x="1064" y="431" font-family="Inter,Arial,sans-serif" font-size="15" font-weight="700" fill="#e5e7eb">wrist RGB-D synthetic feed</text>',
            '<rect x="1064" y="452" width="292" height="134" rx="10" fill="#111827" stroke="#475569"/>',
            '<path d="M1086 584 C1128 505, 1256 506, 1328 584" fill="#64748b" opacity="0.68"/>',
            '<line x1="1130" y1="578" x2="1184" y2="512" stroke="#e5e7eb" stroke-width="9" stroke-linecap="round"/>',
            '<line x1="1262" y1="512" x2="1316" y2="578" stroke="#e5e7eb" stroke-width="9" stroke-linecap="round"/>',
            task_shape,
            f'<circle cx="1334" cy="430" r="6" fill="{event}" filter="url(#glow)"/>',
            '<text x="1064" y="610" font-family="Inter,Arial,sans-serif" font-size="11" fill="#94a3b8">depth confidence, gripper aperture, contact envelope</text>',
            "</g>",
        ]
    )


def render_depth_panel(frame: SimFrame, task: str) -> str:
    cells = []
    for row in range(4):
        for col in range(8):
            value = (row * 8 + col + frame.index) % 9
            color = ["#082f49", "#0e7490", "#0891b2", "#22d3ee", "#67e8f9"][value % 5]
            cells.append(f'<rect x="{1064 + col * 23}" y="{676 + row * 21}" width="18" height="16" rx="3" fill="{color}" opacity="{0.35 + 0.06 * value:.2f}"/>')
    return "\n".join(
        [
            '<g filter="url(#softShadow)">',
            '<rect x="1040" y="650" width="340" height="174" rx="18" fill="#0f172a" opacity="0.88" stroke="#334155"/>',
            '<text x="1064" y="676" font-family="Inter,Arial,sans-serif" font-size="15" font-weight="700" fill="#e5e7eb">local occupancy crop</text>',
            *cells,
            '<rect x="1270" y="690" width="70" height="70" rx="35" fill="none" stroke="#f87171" stroke-width="2" stroke-dasharray="6 5"/>',
            '<text x="1064" y="800" font-family="Inter,Arial,sans-serif" font-size="11" fill="#94a3b8">blue = free/observed · red ring = peer exclusion volume</text>',
            "</g>",
        ]
    )


def text(x: float, y: float, value: object, klass: str = "label", anchor: str = "middle") -> str:
    return f'<text x="{x:.1f}" y="{y:.1f}" class="{klass}" text-anchor="{anchor}">{html.escape(str(value))}</text>'


def write_sim_gallery(run_dir: Path, frame_records: list[dict[str, object]]) -> None:
    lines = [
        f"# Simulated AURORA Run: `{run_dir.name}`",
        "",
        "These frames are synthetic simulation outputs, not real robot camera data.",
        "",
    ]
    for record in frame_records:
        lines.append(f'![{record["phase"]}]({record["file"]})')
        lines.append("")
    (run_dir / "gallery.md").write_text("\n".join(lines), encoding="utf-8")


def write_contact_sheet(run_dir: Path, frame_records: list[dict[str, object]], width: int, height: int) -> None:
    columns = 3
    thumb_w, thumb_h = 300, 193
    pad = 22
    rows = math.ceil(len(frame_records) / columns)
    sheet_w = columns * thumb_w + (columns + 1) * pad
    sheet_h = rows * (thumb_h + 42) + 82
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{sheet_w}" height="{sheet_h}" viewBox="0 0 {sheet_w} {sheet_h}">',
        '<rect width="100%" height="100%" fill="#f8fafc"/>',
        '<text x="22" y="38" font-family="Inter,Arial,sans-serif" font-size="24" font-weight="700" fill="#111827">Simulated AURORA run contact sheet</text>',
        '<text x="22" y="61" font-family="Inter,Arial,sans-serif" font-size="13" fill="#64748b">Synthetic frames, not real robot images</text>',
    ]
    for idx, record in enumerate(frame_records):
        row = idx // columns
        col = idx % columns
        x = pad + col * (thumb_w + pad)
        y = 88 + row * (thumb_h + 42)
        parts.append(f'<rect x="{x}" y="{y}" width="{thumb_w}" height="{thumb_h}" rx="7" fill="#e2e8f0" stroke="#94a3b8"/>')
        parts.append(f'<image href="{record["file"]}" x="{x}" y="{y}" width="{thumb_w}" height="{thumb_h}" preserveAspectRatio="xMidYMid meet"/>')
        parts.append(f'<text x="{x}" y="{y + thumb_h + 22}" font-family="Inter,Arial,sans-serif" font-size="12" fill="#334155">{html.escape(str(record["phase"]))} · t={record["time_s"]}s</text>')
    parts.append("</svg>")
    (run_dir / "contact_sheet.svg").write_text("\n".join(parts), encoding="utf-8")
