from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import html
import json
import math
import random
from datetime import datetime, timezone


TASKS = {
    "handoff": "Collaborative handoff",
    "clutter_tool": "Clutter clearing + tool retrieval",
    "drawer_tool": "Drawer opening + tool retrieval",
    "language": "Zero-shot language retarget",
}


@dataclass(frozen=True)
class SimRunConfig:
    run_id: str
    task: str
    output_dir: Path
    frames: int = 14
    seed: int = 145
    width: int = 1120
    height: int = 720


@dataclass(frozen=True)
class Pose:
    x: float
    y: float
    theta: float = 0.0


@dataclass(frozen=True)
class SimFrame:
    index: int
    time_s: float
    phase: str
    robot_a: Pose
    robot_b: Pose
    tool: Pose
    drawer_open: float
    safety_veto: str | None
    success_estimate: float
    intent_age_ms: float


def safe_run_id(value: str) -> str:
    keep: list[str] = []
    dash = False
    for char in value.strip().lower():
        if char.isalnum() or char in {"_", "-"}:
            keep.append(char)
            dash = char == "-"
        elif not dash:
            keep.append("-")
            dash = True
    return "".join(keep).strip("-") or "sim-run"


def simulate_run(config: SimRunConfig) -> dict[str, object]:
    if config.task not in TASKS:
        raise ValueError(f"unknown task {config.task!r}; choose one of {sorted(TASKS)}")
    if config.frames < 2:
        raise ValueError("frames must be >= 2")

    run_id = safe_run_id(config.run_id)
    run_dir = config.output_dir / run_id
    frames_dir = run_dir / "frames"
    frames_dir.mkdir(parents=True, exist_ok=True)

    rng = random.Random(config.seed)
    frames = generate_frames(config.task, config.frames, rng)
    frame_records: list[dict[str, object]] = []
    for frame in frames:
        frame_path = frames_dir / f"frame_{frame.index:04d}.svg"
        frame_path.write_text(render_frame(frame, config.task, config.width, config.height), encoding="utf-8")
        frame_records.append(
            {
                "file": str(frame_path.relative_to(run_dir)),
                "time_s": frame.time_s,
                "phase": frame.phase,
                "drawer_open": round(frame.drawer_open, 3),
                "safety_veto": frame.safety_veto,
                "success_estimate": round(frame.success_estimate, 3),
                "intent_age_ms": round(frame.intent_age_ms, 1),
            }
        )

    write_sim_gallery(run_dir, frame_records)
    write_contact_sheet(run_dir, frame_records, config.width, config.height)
    manifest = {
        "run_id": run_id,
        "task": config.task,
        "task_label": TASKS[config.task],
        "created_at": datetime.now(timezone.utc).isoformat(),
        "seed": config.seed,
        "frames": frame_records,
        "note": "Synthetic simulation frames generated by the repository reference simulator; not real robot camera data.",
    }
    (run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def generate_frames(task: str, count: int, rng: random.Random) -> list[SimFrame]:
    frames: list[SimFrame] = []
    for idx in range(1, count + 1):
        alpha = (idx - 1) / (count - 1)
        time_s = round(alpha * 18.0, 2)
        intent_age = 80.0 + 140.0 * abs(math.sin(alpha * math.pi * 2.0 + 0.4))
        veto: str | None = None
        drawer_open = 0.0
        success = 0.15 + 0.70 * alpha

        if task == "handoff":
            phase = _phase(alpha, ["APPROACH", "ALIGN", "FORCE_GATE", "TRANSFER", "RETREAT"])
            robot_a = Pose(270 + 160 * alpha, 415 - 45 * alpha, 0.1)
            robot_b = Pose(830 - 210 * alpha, 300 + 60 * alpha, 3.0)
            tool = Pose(445 + 155 * min(1.0, max(0.0, (alpha - 0.35) / 0.45)), 385 + 5 * math.sin(alpha * 8))
            if 0.46 < alpha < 0.56:
                veto = "FORCE_GATE_ARMED"
            success = 0.25 + 0.55 * alpha
        elif task == "clutter_tool":
            phase = _phase(alpha, ["SCAN", "CLEAR_LEFT", "CLEAR_RIGHT", "GRASP_TOOL", "RETRIEVE"])
            robot_a = Pose(250 + 95 * math.sin(alpha * math.pi), 250 + 135 * alpha, 0.8)
            robot_b = Pose(790 - 190 * alpha, 520 - 140 * alpha, -2.5)
            tool = Pose(720 - 190 * alpha, 350 + 40 * math.sin(alpha * 4.0))
            if 0.25 < alpha < 0.36:
                veto = "PEER_EXCLUSION_CLIP"
            success = 0.22 + 0.50 * alpha
        elif task == "drawer_tool":
            phase = _phase(alpha, ["HANDLE_SEARCH", "CENTER_PULL", "RECENTER", "OPEN", "RETRIEVE"])
            robot_a = Pose(330 + 255 * alpha, 490 - 140 * alpha, -0.6)
            robot_b = Pose(780, 520 - 110 * alpha, -2.2)
            drawer_open = min(1.0, max(0.0, (alpha - 0.32) / 0.55))
            tool = Pose(820 - 170 * drawer_open, 258 + 6 * math.sin(alpha * 9.0))
            if 0.48 < alpha < 0.58:
                veto = "DRAWER_SIDE_LOAD"
                success -= 0.08
            success = 0.18 + 0.48 * alpha
        else:
            phase = _phase(alpha, ["LANGUAGE_GROUND", "ROLE_ASSIGN", "BASE_MOVE", "MANIPULATE", "VERIFY"])
            robot_a = Pose(230 + 220 * alpha, 180 + 130 * alpha, 0.6)
            robot_b = Pose(860 - 240 * alpha, 555 - 160 * alpha, 2.7)
            tool = Pose(670 - 80 * alpha, 300 + 110 * alpha)
            if intent_age > 205:
                veto = "STALE_INTENT_HOLD"
            success = 0.20 + 0.50 * alpha

        jitter = lambda amount: rng.uniform(-amount, amount)
        frames.append(
            SimFrame(
                index=idx,
                time_s=time_s,
                phase=phase,
                robot_a=Pose(robot_a.x + jitter(3), robot_a.y + jitter(3), robot_a.theta),
                robot_b=Pose(robot_b.x + jitter(3), robot_b.y + jitter(3), robot_b.theta),
                tool=Pose(tool.x + jitter(4), tool.y + jitter(4), tool.theta),
                drawer_open=drawer_open,
                safety_veto=veto,
                success_estimate=max(0.0, min(0.95, success)),
                intent_age_ms=intent_age,
            )
        )
    return frames


def _phase(alpha: float, phases: list[str]) -> str:
    idx = min(len(phases) - 1, int(alpha * len(phases)))
    return phases[idx]


def render_frame(frame: SimFrame, task: str, width: int, height: int) -> str:
    title = TASKS[task]
    body = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        "<style>text{font-family:Inter,Arial,sans-serif}.title{font-size:24px;font-weight:700;fill:#111827}.label{font-size:14px;fill:#334155}.small{font-size:12px;fill:#64748b}.hud{font-size:13px;fill:#0f172a}.wall{fill:#e2e8f0;stroke:#475569;stroke-width:3}.floor{fill:#f8fafc}.zone{fill:#dbeafe;stroke:#2563eb;stroke-width:1;opacity:.55}.danger{fill:#fee2e2;stroke:#dc2626;stroke-width:1}.drawer{fill:#fef3c7;stroke:#92400e;stroke-width:2}.clutter{fill:#cbd5e1;stroke:#64748b;stroke-width:1}.tool{fill:#f97316;stroke:#9a3412;stroke-width:2}.robotA{fill:#2563eb;stroke:#1e3a8a;stroke-width:3}.robotB{fill:#16a34a;stroke:#14532d;stroke-width:3}.arm{stroke:#0f172a;stroke-width:6;stroke-linecap:round}.grip{stroke:#111827;stroke-width:3}</style>",
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        text(32, 38, f"{title} · simulated frame {frame.index:02d}", "title", "start"),
        text(32, 63, "Synthetic AURORA simulator output, not real robot camera data", "small", "start"),
        '<rect x="40" y="90" width="760" height="560" rx="8" class="floor" stroke="#94a3b8" stroke-width="2"/>',
        '<rect x="70" y="128" width="700" height="36" class="wall"/>',
        '<rect x="70" y="602" width="700" height="26" class="wall"/>',
        '<rect x="70" y="128" width="30" height="500" class="wall"/>',
        '<rect x="740" y="128" width="30" height="500" class="wall"/>',
        '<rect x="118" y="196" width="176" height="82" rx="8" fill="#d1d5db" stroke="#64748b"/>',
        '<rect x="570" y="190" width="150" height="245" rx="8" fill="#e5e7eb" stroke="#64748b"/>',
        f'<rect x="{610 - 75 * frame.drawer_open:.1f}" y="230" width="{120 + 75 * frame.drawer_open:.1f}" height="68" rx="4" class="drawer"/>',
        '<rect x="360" y="330" width="128" height="82" rx="8" fill="#fde68a" stroke="#a16207"/>',
        '<ellipse cx="430" cy="370" rx="155" ry="115" class="zone"/>',
        '<circle cx="610" cy="370" r="92" class="danger" opacity=".35"/>',
    ]
    for i, (x, y, rot) in enumerate([(390, 350, 20), (420, 395, -15), (455, 345, 70), (500, 383, 35), (535, 335, -30)]):
        body.append(f'<rect x="{x}" y="{y}" width="{38 + i * 3}" height="{18 + (i % 2) * 12}" rx="4" class="clutter" transform="rotate({rot} {x} {y})"/>')
    body.append(render_tool(frame.tool, task))
    body.append(render_robot(frame.robot_a, "A", "robotA"))
    body.append(render_robot(frame.robot_b, "B", "robotB"))
    body.extend(render_hud(frame))
    body.extend(render_wrist_inset(frame, task))
    body.append("</svg>")
    return "\n".join(body)


def render_robot(pose: Pose, label: str, klass: str) -> str:
    arm_len = 62
    ex = pose.x + arm_len * math.cos(pose.theta)
    ey = pose.y + arm_len * math.sin(pose.theta)
    return "\n".join(
        [
            f'<circle cx="{pose.x:.1f}" cy="{pose.y:.1f}" r="34" class="{klass}"/>',
            f'<line x1="{pose.x:.1f}" y1="{pose.y:.1f}" x2="{ex:.1f}" y2="{ey:.1f}" class="arm"/>',
            f'<line x1="{ex - 10:.1f}" y1="{ey - 9:.1f}" x2="{ex + 10:.1f}" y2="{ey + 9:.1f}" class="grip"/>',
            text(pose.x, pose.y + 5, f"R{label}", "label"),
        ]
    )


def render_tool(pose: Pose, task: str) -> str:
    if task == "handoff":
        return f'<rect x="{pose.x-34:.1f}" y="{pose.y-8:.1f}" width="68" height="16" rx="8" class="tool"/><circle cx="{pose.x+24:.1f}" cy="{pose.y:.1f}" r="15" fill="#fde68a" stroke="#9a3412" stroke-width="2"/>'
    if task == "drawer_tool":
        return f'<path d="M {pose.x-42:.1f} {pose.y:.1f} L {pose.x+34:.1f} {pose.y:.1f}" class="tool" stroke-width="9" stroke-linecap="round"/><circle cx="{pose.x+38:.1f}" cy="{pose.y:.1f}" r="12" class="tool"/>'
    return f'<path d="M {pose.x-38:.1f} {pose.y+15:.1f} L {pose.x+35:.1f} {pose.y-18:.1f}" class="tool" stroke-width="8" stroke-linecap="round"/><rect x="{pose.x+22:.1f}" y="{pose.y-28:.1f}" width="28" height="18" rx="3" class="tool"/>'


def render_hud(frame: SimFrame) -> list[str]:
    x, y = 840, 96
    veto = frame.safety_veto or "none"
    rows = [
        ("phase", frame.phase),
        ("intent age", f"{frame.intent_age_ms:.0f} ms"),
        ("drawer open", f"{frame.drawer_open:.2f}"),
        ("success est.", f"{frame.success_estimate:.2f}"),
        ("safety event", veto),
    ]
    body = [
        '<rect x="820" y="90" width="260" height="190" rx="8" fill="#f8fafc" stroke="#94a3b8"/>',
        text(950, 120, "Runtime telemetry", "label"),
    ]
    for idx, (key, value) in enumerate(rows):
        body.append(text(x, y + 56 + idx * 25, key, "small", "start"))
        body.append(text(1060, y + 56 + idx * 25, value, "hud", "end"))
    return body


def render_wrist_inset(frame: SimFrame, task: str) -> list[str]:
    body = [
        '<rect x="820" y="310" width="260" height="260" rx="8" fill="#111827" stroke="#475569" stroke-width="2"/>',
        text(950, 338, "synthetic wrist view", "small"),
        '<rect x="850" y="365" width="200" height="120" rx="6" fill="#374151"/>',
        '<path d="M 875 530 C 910 455, 995 455, 1030 530" fill="#94a3b8" stroke="#e5e7eb" stroke-width="2"/>',
        '<line x1="905" y1="505" x2="940" y2="452" stroke="#e5e7eb" stroke-width="8" stroke-linecap="round"/>',
        '<line x1="995" y1="452" x2="1030" y2="505" stroke="#e5e7eb" stroke-width="8" stroke-linecap="round"/>',
    ]
    if task == "drawer_tool":
        body.append(f'<rect x="{915 - 34 * frame.drawer_open:.1f}" y="404" width="{86 + 45 * frame.drawer_open:.1f}" height="34" rx="4" fill="#fbbf24" stroke="#92400e"/>')
        body.append('<circle cx="940" cy="421" r="8" fill="#111827"/>')
    elif task == "handoff":
        body.append('<rect x="912" y="410" width="78" height="18" rx="9" fill="#f97316" stroke="#fed7aa"/>')
    else:
        body.append('<path d="M 905 435 L 990 397" stroke="#f97316" stroke-width="8" stroke-linecap="round"/>')
    return body


def text(x: float, y: float, value: object, klass: str = "label", anchor: str = "middle") -> str:
    return f'<text x="{x:.1f}" y="{y:.1f}" class="{klass}" text-anchor="{anchor}">{html.escape(str(value))}</text>'


def write_sim_gallery(run_dir: Path, frame_records: list[dict[str, object]]) -> None:
    lines = [
        f"# Simulated AURORA Run: `{run_dir.name}`",
        "",
        "These frames are synthetic simulation outputs, not real robot camera data.",
        "",
    ]
    for record in frame_records:
        lines.append(f'![{record["phase"]}]({record["file"]})')
        lines.append("")
    (run_dir / "gallery.md").write_text("\n".join(lines), encoding="utf-8")


def write_contact_sheet(run_dir: Path, frame_records: list[dict[str, object]], width: int, height: int) -> None:
    columns = 3
    thumb_w, thumb_h = 300, 193
    pad = 22
    rows = math.ceil(len(frame_records) / columns)
    sheet_w = columns * thumb_w + (columns + 1) * pad
    sheet_h = rows * (thumb_h + 42) + 82
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{sheet_w}" height="{sheet_h}" viewBox="0 0 {sheet_w} {sheet_h}">',
        '<rect width="100%" height="100%" fill="#f8fafc"/>',
        '<text x="22" y="38" font-family="Inter,Arial,sans-serif" font-size="24" font-weight="700" fill="#111827">Simulated AURORA run contact sheet</text>',
        '<text x="22" y="61" font-family="Inter,Arial,sans-serif" font-size="13" fill="#64748b">Synthetic frames, not real robot images</text>',
    ]
    for idx, record in enumerate(frame_records):
        row = idx // columns
        col = idx % columns
        x = pad + col * (thumb_w + pad)
        y = 88 + row * (thumb_h + 42)
        parts.append(f'<rect x="{x}" y="{y}" width="{thumb_w}" height="{thumb_h}" rx="7" fill="#e2e8f0" stroke="#94a3b8"/>')
        parts.append(f'<image href="{record["file"]}" x="{x}" y="{y}" width="{thumb_w}" height="{thumb_h}" preserveAspectRatio="xMidYMid meet"/>')
        parts.append(f'<text x="{x}" y="{y + thumb_h + 22}" font-family="Inter,Arial,sans-serif" font-size="12" fill="#334155">{html.escape(str(record["phase"]))} · t={record["time_s"]}s</text>')
    parts.append("</svg>")
    (run_dir / "contact_sheet.svg").write_text("\n".join(parts), encoding="utf-8")
